[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/fenix-functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
