import type { BlockCategory, BlockDefinition, BlockType } from "./types";

export const CATEGORY_LABELS: Record<BlockCategory, string> = {
  basic: "Basic",
  profile: "Profile",
  media: "Media",
  business: "Business",
  conversion: "Conversion",
  navigation: "Navigation",
  advanced: "Advanced",
};

export const CATEGORY_ORDER: BlockCategory[] = [
  "basic",
  "profile",
  "media",
  "business",
  "conversion",
  "navigation",
  "advanced",
];

/**
 * The full block catalog. Blocks marked `status: "ready"` have a working
 * renderer + editor and are addable. `soon` blocks are shown greyed-out so the
 * roadmap is transparent, but cannot be added (per the spec: only show a block
 * in production when its minimum workflow works).
 */
export const BLOCK_REGISTRY: Record<BlockType, BlockDefinition> = {
  // Basic --------------------------------------------------------------------
  heading: {
    type: "heading",
    name: "Heading",
    description: "A large title to structure your page.",
    category: "basic",
    icon: "Heading",
    status: "ready",
    defaultContent: { text: "Your heading", level: 2 },
  },
  text: {
    type: "text",
    name: "Text",
    description: "A paragraph of formatted text.",
    category: "basic",
    icon: "Type",
    status: "ready",
    defaultContent: { text: "Write something about yourself or your business." },
  },
  button: {
    type: "button",
    name: "Button",
    description: "A single call-to-action button with a link.",
    category: "basic",
    icon: "MousePointerClick",
    status: "ready",
    defaultContent: { label: "Open link", url: "https://", style: "solid" },
  },
  link: {
    type: "link",
    name: "Link",
    description: "A tappable link card with an optional subtitle.",
    category: "basic",
    icon: "Link",
    status: "ready",
    defaultContent: { title: "My link", subtitle: "", url: "https://" },
  },
  "link-list": {
    type: "link-list",
    name: "Multiple links",
    description: "A group of links shown as a stacked list.",
    category: "basic",
    icon: "List",
    status: "ready",
    defaultContent: {
      items: [
        { id: "1", title: "First link", url: "https://" },
        { id: "2", title: "Second link", url: "https://" },
      ],
    },
  },
  divider: {
    type: "divider",
    name: "Divider",
    description: "A thin horizontal separator.",
    category: "basic",
    icon: "Minus",
    status: "ready",
    defaultContent: {},
  },
  spacer: {
    type: "spacer",
    name: "Spacer",
    description: "Adjustable vertical spacing.",
    category: "basic",
    icon: "MoveVertical",
    status: "ready",
    defaultContent: { size: 24 },
  },
  "icon-text": {
    type: "icon-text",
    name: "Icon & text",
    description: "An icon paired with a short line of text.",
    category: "basic",
    icon: "Sparkles",
    status: "ready",
    defaultContent: { icon: "Star", text: "Highlight something" },
  },
  // Profile ------------------------------------------------------------------
  avatar: {
    type: "avatar",
    name: "Avatar",
    description: "A circular profile image.",
    category: "profile",
    icon: "CircleUser",
    status: "ready",
    defaultContent: { url: "", size: "lg" },
  },
  "profile-header": {
    type: "profile-header",
    name: "Profile header",
    description: "Avatar, name and a short bio in one block.",
    category: "profile",
    icon: "IdCard",
    status: "ready",
    defaultContent: {
      avatarUrl: "",
      name: "Your name",
      bio: "A short line about you or your brand.",
    },
  },
  "contact-details": {
    type: "contact-details",
    name: "Contact details",
    description: "A compact list of contact methods.",
    category: "profile",
    icon: "Contact",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", type: "phone", value: "+998 90 000 00 00" }],
    },
  },
  "social-links": {
    type: "social-links",
    name: "Social networks",
    description: "A row of social network icons.",
    category: "profile",
    icon: "Share2",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", network: "instagram", url: "https://instagram.com/" }],
    },
  },
  messengers: {
    type: "messengers",
    name: "Messengers",
    description: "Quick links to messenger apps.",
    category: "profile",
    icon: "MessageCircle",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", app: "telegram", value: "https://t.me/" }],
    },
  },
  phone: {
    type: "phone",
    name: "Phone",
    description: "A tap-to-call phone number.",
    category: "profile",
    icon: "Phone",
    status: "ready",
    defaultContent: { number: "+998 90 000 00 00", label: "Call us" },
  },
  email: {
    type: "email",
    name: "Email",
    description: "A tap-to-email address.",
    category: "profile",
    icon: "Mail",
    status: "ready",
    defaultContent: { address: "hello@example.com", label: "Email us" },
  },
  address: {
    type: "address",
    name: "Address",
    description: "A physical address line.",
    category: "profile",
    icon: "MapPin",
    status: "ready",
    defaultContent: { text: "Tashkent, Uzbekistan" },
  },
  "working-hours": {
    type: "working-hours",
    name: "Working hours",
    description: "A weekly opening-hours table.",
    category: "profile",
    icon: "Clock",
    status: "ready",
    defaultContent: {
      rows: [{ id: "1", day: "Mon–Fri", hours: "09:00 – 18:00" }],
    },
  },
  // Media --------------------------------------------------------------------
  image: {
    type: "image",
    name: "Image",
    description: "A single image with optional caption.",
    category: "media",
    icon: "Image",
    status: "ready",
    defaultContent: { url: "", alt: "", caption: "" },
  },
  gallery: {
    type: "gallery",
    name: "Image gallery",
    description: "A grid of images.",
    category: "media",
    icon: "Images",
    status: "ready",
    defaultContent: { images: [] },
  },
  youtube: {
    type: "youtube",
    name: "YouTube",
    description: "An embedded YouTube video.",
    category: "media",
    icon: "Youtube",
    status: "ready",
    defaultContent: { url: "" },
  },
  video: {
    type: "video",
    name: "Video",
    description: "An embedded video from a URL.",
    category: "media",
    icon: "Video",
    status: "soon",
    defaultContent: { url: "" },
  },
  audio: {
    type: "audio",
    name: "Audio",
    description: "An embedded audio player.",
    category: "media",
    icon: "Music",
    status: "soon",
    defaultContent: { url: "" },
  },
  file: {
    type: "file",
    name: "File download",
    description: "A downloadable file button.",
    category: "media",
    icon: "FileDown",
    status: "ready",
    defaultContent: { url: "", label: "Download file" },
  },
  banner: {
    type: "banner",
    name: "Banner",
    description: "A full-width promotional banner.",
    category: "media",
    icon: "GalleryHorizontalEnd",
    status: "ready",
    defaultContent: { url: "", link: "" },
  },
  carousel: {
    type: "carousel",
    name: "Carousel",
    description: "A swipeable set of slides.",
    category: "media",
    icon: "GalleryHorizontal",
    status: "soon",
    defaultContent: { slides: [] },
  },
  // Business -----------------------------------------------------------------
  services: {
    type: "services",
    name: "Services",
    description: "A list of services with prices.",
    category: "business",
    icon: "BriefcaseBusiness",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", title: "Service", price: "", description: "" }],
    },
  },
  "price-list": {
    type: "price-list",
    name: "Price list",
    description: "A simple two-column price list.",
    category: "business",
    icon: "ReceiptText",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", label: "Item", price: "0" }],
    },
  },
  faq: {
    type: "faq",
    name: "FAQ",
    description: "Expandable question-and-answer items.",
    category: "business",
    icon: "CircleHelp",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", question: "Question?", answer: "Answer." }],
    },
  },
  reviews: {
    type: "reviews",
    name: "Reviews",
    description: "Customer testimonials.",
    category: "business",
    icon: "Quote",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", author: "Customer", text: "Great service!", rating: 5 }],
    },
  },
  team: {
    type: "team",
    name: "Team members",
    description: "Introduce your team.",
    category: "business",
    icon: "Users",
    status: "ready",
    defaultContent: {
      items: [{ id: "1", name: "Team member", role: "Role", avatar: "" }],
    },
  },
  countdown: {
    type: "countdown",
    name: "Countdown",
    description: "A live countdown to a date.",
    category: "business",
    icon: "TimerReset",
    status: "ready",
    defaultContent: { target: "", title: "Launching soon" },
  },
  product: {
    type: "product",
    name: "Product",
    description: "A single product card.",
    category: "business",
    icon: "Package",
    status: "soon",
    defaultContent: {},
  },
  "product-grid": {
    type: "product-grid",
    name: "Product grid",
    description: "A grid of products from your catalog.",
    category: "business",
    icon: "LayoutGrid",
    status: "soon",
    defaultContent: {},
  },
  menu: {
    type: "menu",
    name: "Restaurant menu",
    description: "Categorized menu with dishes and prices.",
    category: "business",
    icon: "UtensilsCrossed",
    status: "soon",
    defaultContent: {},
  },
  map: {
    type: "map",
    name: "Map",
    description: "An embedded location map.",
    category: "business",
    icon: "Map",
    status: "ready",
    defaultContent: { query: "Tashkent" },
  },
  // Conversion ---------------------------------------------------------------
  form: {
    type: "form",
    name: "Form",
    description: "Collect leads with a custom form.",
    category: "conversion",
    icon: "FormInput",
    status: "ready",
    defaultContent: { formId: null, title: "Contact us" },
  },
  cta: {
    type: "cta",
    name: "Call to action",
    description: "A bold prompt with a button.",
    category: "conversion",
    icon: "Megaphone",
    status: "ready",
    defaultContent: { title: "Ready to start?", label: "Get started", url: "https://" },
  },
  newsletter: {
    type: "newsletter",
    name: "Newsletter",
    description: "An email subscription block.",
    category: "conversion",
    icon: "MailPlus",
    status: "ready",
    defaultContent: { title: "Subscribe", placeholder: "Your email" },
  },
  payment: {
    type: "payment",
    name: "Payment button",
    description: "Accept a payment (requires configuration).",
    category: "conversion",
    icon: "CreditCard",
    status: "soon",
    premium: true,
    defaultContent: {},
  },
  appointment: {
    type: "appointment",
    name: "Appointment request",
    description: "Let visitors request a time slot.",
    category: "conversion",
    icon: "CalendarClock",
    status: "soon",
    defaultContent: {},
  },
  order: {
    type: "order",
    name: "Order request",
    description: "Take an order request.",
    category: "conversion",
    icon: "ShoppingCart",
    status: "soon",
    defaultContent: {},
  },
  // Navigation ---------------------------------------------------------------
  "internal-page": {
    type: "internal-page",
    name: "Internal page",
    description: "Link to another page in this site.",
    category: "navigation",
    icon: "FileSymlink",
    status: "ready",
    defaultContent: { title: "Go to page", targetSlug: "" },
  },
  "external-page": {
    type: "external-page",
    name: "External page",
    description: "Link to an external website.",
    category: "navigation",
    icon: "ExternalLink",
    status: "ready",
    defaultContent: { title: "Open website", url: "https://" },
  },
  "custom-url": {
    type: "custom-url",
    name: "Custom URL",
    description: "A raw URL link.",
    category: "navigation",
    icon: "Globe",
    status: "ready",
    defaultContent: { title: "Link", url: "https://" },
  },
  anchor: {
    type: "anchor",
    name: "Section anchor",
    description: "Jump to a section on this page.",
    category: "navigation",
    icon: "Anchor",
    status: "soon",
    defaultContent: {},
  },
  // Advanced -----------------------------------------------------------------
  html: {
    type: "html",
    name: "HTML block",
    description: "Insert sanitized custom HTML.",
    category: "advanced",
    icon: "Code",
    status: "ready",
    premium: true,
    defaultContent: { html: "<p>Custom HTML</p>" },
  },
  embed: {
    type: "embed",
    name: "Embed",
    description: "Embed content from a URL.",
    category: "advanced",
    icon: "SquareCode",
    status: "ready",
    defaultContent: { url: "" },
  },
  code: {
    type: "code",
    name: "Custom code",
    description: "Advanced custom code block.",
    category: "advanced",
    icon: "Terminal",
    status: "soon",
    premium: true,
    defaultContent: {},
  },
  layout: {
    type: "layout",
    name: "Custom layout",
    description: "A multi-column layout container.",
    category: "advanced",
    icon: "Columns3",
    status: "soon",
    defaultContent: {},
  },
};

export const ALL_BLOCKS: BlockDefinition[] = Object.values(BLOCK_REGISTRY);

export function getBlockDefinition(type: string): BlockDefinition | undefined {
  return BLOCK_REGISTRY[type as BlockType];
}

export function isBlockReady(type: string): boolean {
  return getBlockDefinition(type)?.status === "ready";
}
